#!/bin/sh

CONF_DIR="/root/skrypty/etc"

source ${CONF_DIR}/main.conf

echo " * Generuje dhcpd.conf.hosts"
echo "# Generated by ${0}" > ${DHCPHOSTS_FILE}

egrep -v '^($|#)' ${CONF_DIR}/hosts.conf | awk '$5 == "1" { print $0 }' | while read LINE
do
	IP=$(echo $LINE | awk '{ print $1 }')
	MAC=$(echo $LINE | awk '{ print $2 }')
	NAME=$(echo $LINE | awk '{ print $3 }')

	echo -e " *  ${NAME}: ${MAC} => ${IP}"
	
	cat >> ${DHCPHOSTS_FILE} <<EOF
host ${NAME} {
	fixed-address ${IP};
	hardware ethernet ${MAC};
}

EOF
done

/etc/init.d/dhcpd restart
